app/models.py
from .extentions import db
from datetime import datetime

class Article(db.Model):
    # Имя таблицы в базе данных
    __tablename__ = 'articles'

    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text, nullable=False)
    date = db.Column(db.String, default=datetime.now().strftime("%B %d, %Y"))
    title = db.Column(db.String(50), nullable=False)

app/__init__.py
from flask import Flask
from .extentions import db, migrate
from .routes.index import main
from .routes.Post import Post
from .routes.autorization import autoriz
from .routes.LogOut import LogOut
from .config import *


def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = config.URI
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SECRET_KEY'] = config.SECRET_KEY

    app.register_blueprint(LogOut)
    app.register_blueprint(main)
    app.register_blueprint(Post)
    app.register_blueprint(autoriz)

    db.init_app(app)
    migrate.init_app(app, db)

    with app.app_context():
        db.create_all()
    return app

app/routes/LogOut.py
from flask import Blueprint, render_template, request, redirect, flash, session
from ..extentions import db
from ..config import PASSWORD, LOGINN

LogOut = Blueprint('LogOut', __name__)

@LogOut.route("/LogOut")
def LOGOUT():
    session.pop('user', None)  # Удаляем пользователя из сессии
    session.pop('role', None)  # Удаляем роль
    return redirect('/')
    

app/routes/Post.py
from flask import Blueprint, render_template, request, redirect, flash
from ..extentions import db
from ..models import Article


Post = Blueprint('Post', __name__)

@Post.route("/CreatePost", methods=["POST", "GET"])
def Create():
    if request.method == "POST":
        title = request.form["title"]
        text = request.form["text"]
        post = Article(title=title, text=text) 
        
        try:
            db.session.add(post)
            db.session.commit()
            return redirect("/")
        except Exception as e: 
            db.session.rollback()
            print("произошла ошибка: ", str(e))
            return redirect("/CreatePost")
        finally:
            db.session.remove()
    else:
        return render_template("CreatePost.html")
    

@Post.route("/<int:id>/EditPost", methods=["POST", "GET"])
def Edit(id):
    post = Article.query.get(id)
    if request.method == "POST":
        post.title = request.form["title"]
        post.text = request.form["text"]

        try:
            db.session.commit()
            return redirect("/")
        except Exception as e: 
            db.session.rollback()
            print("произошла ошибка: ", str(e))
            return redirect("/CreatePost")
        finally:
            db.session.remove()


    else:
        return render_template("EditPost.html", post_title=post.title, post_text=post.text)
    


@Post.route("/<int:id>/Delete")
def Delete(id):
    post = Article.query.get(id)

    try:
        db.session.delete(post)
        db.session.commit()
        return redirect("/")
    except Exception as e: 
        db.session.rollback()
        print("произошла ошибка: ", str(e))
        return redirect("/")
    finally:
        db.session.remove()

    

@Post.route("/<int:id>/ARTICLE")
def ARTICLE(id):
    post = Article.query.get(id)
    return render_template("Article.html", post=post)

app/routes/autorization.py
from flask import Blueprint, render_template, request, redirect, flash, session
from ..extentions import db
from ..config import PASSWORD, LOGINN

autoriz = Blueprint('autoriz', __name__)

@autoriz.route("/autorization", methods=["POST", "GET"])
def LOGIN():
    print("rqMethod is ", request.method)
    if request.method == "POST":
        login = str(request.form["login"])
        password = str(request.form["password"])
        if login == LOGINN and password == PASSWORD:
            session['user'] = login  
            session['role'] = 'admin'
            return redirect("/")
        else:
            return redirect("/autorization")
    else:
        return render_template("autorization.html")
    

app/routes/index.py
from flask import Blueprint, render_template, request, redirect, flash, session
from ..extentions import db
from ..models import Article

main = Blueprint('main', __name__)

@main.route("/")
def index():
    posts = reversed(Article.query.all())
    return render_template("index.html", posts=posts)

app/templates/Article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New post</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/blog.css') }}">
</head>
<body>
    <header>
        <div class="container">
            <div class="Header_Navig">
                <div class="Header_Navig_Home">
                    <a href="/" >Home</a>
                </div>
                {% if session['role'] == 'admin' %}
                    <div class="Header_Navig_AdminPanel">
                        <a href="/LogOut">Log out</a>
                    </div>
                    
                {% else %}
                    <div class="Header_Navig_AdminPanel">
                        <a href="/autorization" >Admin panel</a>
                    </div>
                {% endif %}

                
            </div>
        </div>
    </header>
    <section id="article" class="article">
        <div class="article_container">
            <div class="container_inner">
                <div class="container_inner_title">
                    <p class="title">{{ post.title }}</p>
                    <p class="title_date">{{ post.date }}</p>
                </div>
                <div class="text-container">
                    <p class="text">{{ post.text }}</p>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

app/templates/CreatePost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New post</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Create.css') }}">
</head>
<body>
    <header>
        <div class="container">
            <div class="Header_Navig">
                <div class="Header_Navig_Home">
                    <a href="/" >Home</a>
                </div>
                {% if session['role'] == 'admin' %}
                    <div class="Header_Navig_AdminPanel">
                        <a href="/LogOut">Log out</a>
                    </div>
                    
                {% else %}
                    <div class="Header_Navig_AdminPanel">
                        <a href="/autorization" >Admin panel</a>
                    </div>
                {% endif %}

                
            </div>
        </div>
    </header>
    <section id="article" class="article">
        <div class="article_container">
            <div class="container_inner">
                <form method="POST" class="form-control">
                    <p class="title">New post</p>
                    <input name="title" type="text" placeholder="title" class="form-control-input-title" required>
                    <textarea name="text" type="text" placeholder="enter text" class="form-control-input-text" required></textarea>
                    <input type="submit" value="publish post" class="btn-succsess">
                </form>
            </div>
        </div>
    </section>
</body>
</html>

app/templates/EditPost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New post</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Create.css') }}">
</head>
<body>
    <header>
        <div class="container">
            <div class="Header_Navig">
                <div class="Header_Navig_Home">
                    <a href="/" >Home</a>
                </div>
                {% if session['role'] == 'admin' %}
                    <div class="Header_Navig_AdminPanel">
                        <a href="/LogOut">Log out</a>
                    </div>
                    
                {% else %}
                    <div class="Header_Navig_AdminPanel">
                        <a href="/autorization" >Admin panel</a>
                    </div>
                {% endif %}

                
            </div>
        </div>
    </header>
    <section id="article" class="article">
        <div class="article_container">
            <div class="container_inner">
                <form method="POST" class="form-control">
                    <p class="title">Edit post "{{ post_title }}"</p>
                    <input name="title" type="text" placeholder="title" class="form-control-input-title" value="{{ post_title }}" required>
                    <textarea name="text" type="text" placeholder="enter text" class="form-control-input-text" required>{{ post_text }}</textarea>
                    <input type="submit" value="Update post" class="btn-succsess">
                </form>
            </div>
        </div>
    </section>
</body>
</html>

app/templates/LogOut.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
    <header>
        <div class="container">
            <div class="Header_Navig">
                <div class="Header_Navig_Home">
                    <a href="/" >Home</a>
                </div>
                <div class="Header_Navig_AdminPanel">
                    <a href="/CreatePost" >Admin panel</a>
                </div>
            </div>
        </div>
    </header>
    
    <section class="login-sec">
        <form method="POST" class="form-control">
            <p class="title">Log In</p>
            <input name="login" type="text" placeholder="Login" class="form-control-input-title" required>
            <input name="password" type="password" placeholder="Password" class="form-control-input-text" required>
            <input type="submit" value="Enter" class="btn-succsess">
        </form>
    </section>
</body>
</html>

app/templates/autorization.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/login.css') }}">
</head>
<body>
    <header>
        <div class="container">
            <div class="Header_Navig">
                <div class="Header_Navig_Home">
                    <a href="/" >Home</a>
                </div>
                <div class="Header_Navig_AdminPanel">
                    <a href="/CreatePost" >Admin panel</a>
                </div>
            </div>
        </div>
    </header>
    
    <section class="login-sec">
        <div class="container-login">
            <form method="POST" class="form-control">
                <div class="container-login-content">
                    <p class="title">Log In</p>
                    <input name="login" type="text" placeholder="Login" class="form-control-input-title" required>
                    <input name="password" type="password" placeholder="Password" class="form-control-input-text" required>
                    <input type="submit" value="Enter" class="btn-succsess">
                </div>
            </form>
        </div>
    </section>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/table.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/article.css') }}">
</head>
<body>
    <header>
        <div class="container">
            <div class="Header_Navig">
                <div class="Header_Navig_Home">
                    <a href="/" >Home</a>
                </div>
                {% if session['role'] == 'admin' %}
                    <div class="Header_Navig_AdminPanel">
                        <a href="/LogOut">Log out</a>
                    </div>
                    
                {% else %}
                    <div class="Header_Navig_AdminPanel">
                        <a href="/autorization" >Admin panel</a>
                    </div>
                {% endif %}

                
            </div>
        </div>
    </header>
    
    <section id="articles", class="articles">
        <div class="container">
            <div class="articles_container">
                    <div class="articles-navpanel">
                        <h1 class="page_title">Personal blog</h1>
                        {% if session['role'] == 'admin' %}
                            <a class="article_link" href="/CreatePost">Add post</a>
                        {% endif %}
                    </div>
                <table class="articles_table">
                    <thead>
                        <th>Post title</th>
                        <th>Post date</th>
                        
                    </thead>
                    <tbody>
                        {% for post in posts %}
                                <tr>
                                    <td class="td_title">
                                        <a href="{{ url_for('Post.ARTICLE', id=post.id) }}"><div class="post_title">
                                            {{ post.title }}
                                        </div></a>
                                    </td>
                                    <td class="td_date">{{ post.date }}</td>
                                    {% if session['role'] == 'admin' %}
                                        <td class="admin_buttons"><a class="article_link" href="{{ url_for('Post.Edit', id=post.id) }}">Edit</a>
                                            <a class="article_link" href="{{ url_for('Post.Delete', id=post.id) }}">Delete</a>
                                        </td>
                                    {% endif %}
                                </tr>

                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</body>
</html>